use kira::sound::static_sound::StaticSoundData;
use rand::prelude::*;
use rdev::Key::{self, *};

const VOICE_RANGE: std::ops::Range<f64> = 1.3_f64..1.4_f64;

// TODO: Add sounds for special characters
// TODO: Track modifier keys to play special characters, not just the base (e.g., number)
pub struct KeySounds {
    rng: ThreadRng,
    next_playback_rate: f64,
    sound_a: StaticSoundData,
    sound_b: StaticSoundData,
    sound_c: StaticSoundData,
    sound_d: StaticSoundData,
    sound_e: StaticSoundData,
    sound_f: StaticSoundData,
    sound_g: StaticSoundData,
    sound_h: StaticSoundData,
    sound_i: StaticSoundData,
    sound_j: StaticSoundData,
    sound_k: StaticSoundData,
    sound_l: StaticSoundData,
    sound_m: StaticSoundData,
    sound_n: StaticSoundData,
    sound_o: StaticSoundData,
    sound_p: StaticSoundData,
    sound_q: StaticSoundData,
    sound_r: StaticSoundData,
    sound_s: StaticSoundData,
    sound_t: StaticSoundData,
    sound_u: StaticSoundData,
    sound_v: StaticSoundData,
    sound_w: StaticSoundData,
    sound_x: StaticSoundData,
    sound_y: StaticSoundData,
    sound_z: StaticSoundData,
    sound_0: StaticSoundData,
    sound_1: StaticSoundData,
    sound_2: StaticSoundData,
    sound_3: StaticSoundData,
    sound_4: StaticSoundData,
    sound_5: StaticSoundData,
    sound_6: StaticSoundData,
    sound_7: StaticSoundData,
    sound_8: StaticSoundData,
    sound_9: StaticSoundData,
}

impl KeySounds {
    pub fn new() -> Self {
        let mut rng = rand::rng();
        let next_playback_rate = rng.random_range(VOICE_RANGE);
        Self {
            rng,
            next_playback_rate,
            sound_a: StaticSoundData::from_file("sounds/a.ogg").expect("ACK"),
            sound_b: StaticSoundData::from_file("sounds/b.ogg").expect("ACK"),
            sound_c: StaticSoundData::from_file("sounds/c.ogg").expect("ACK"),
            sound_d: StaticSoundData::from_file("sounds/d.ogg").expect("ACK"),
            sound_e: StaticSoundData::from_file("sounds/e.ogg").expect("ACK"),
            sound_f: StaticSoundData::from_file("sounds/f.ogg").expect("ACK"),
            sound_g: StaticSoundData::from_file("sounds/g.ogg").expect("ACK"),
            sound_h: StaticSoundData::from_file("sounds/h.ogg").expect("ACK"),
            sound_i: StaticSoundData::from_file("sounds/i.ogg").expect("ACK"),
            sound_j: StaticSoundData::from_file("sounds/j.ogg").expect("ACK"),
            sound_k: StaticSoundData::from_file("sounds/k.ogg").expect("ACK"),
            sound_l: StaticSoundData::from_file("sounds/l.ogg").expect("ACK"),
            sound_m: StaticSoundData::from_file("sounds/m.ogg").expect("ACK"),
            sound_n: StaticSoundData::from_file("sounds/n.ogg").expect("ACK"),
            sound_o: StaticSoundData::from_file("sounds/o.ogg").expect("ACK"),
            sound_p: StaticSoundData::from_file("sounds/p.ogg").expect("ACK"),
            sound_q: StaticSoundData::from_file("sounds/q.ogg").expect("ACK"),
            sound_r: StaticSoundData::from_file("sounds/r.ogg").expect("ACK"),
            sound_s: StaticSoundData::from_file("sounds/s.ogg").expect("ACK"),
            sound_t: StaticSoundData::from_file("sounds/t.ogg").expect("ACK"),
            sound_u: StaticSoundData::from_file("sounds/u.ogg").expect("ACK"),
            sound_v: StaticSoundData::from_file("sounds/v.ogg").expect("ACK"),
            sound_w: StaticSoundData::from_file("sounds/w.ogg").expect("ACK"),
            sound_x: StaticSoundData::from_file("sounds/x.ogg").expect("ACK"),
            sound_y: StaticSoundData::from_file("sounds/y.ogg").expect("ACK"),
            sound_z: StaticSoundData::from_file("sounds/z.ogg").expect("ACK"),
            sound_0: StaticSoundData::from_file("sounds/0.ogg").expect("ACK"),
            sound_1: StaticSoundData::from_file("sounds/1.ogg").expect("ACK"),
            sound_2: StaticSoundData::from_file("sounds/2.ogg").expect("ACK"),
            sound_3: StaticSoundData::from_file("sounds/3.ogg").expect("ACK"),
            sound_4: StaticSoundData::from_file("sounds/4.ogg").expect("ACK"),
            sound_5: StaticSoundData::from_file("sounds/5.ogg").expect("ACK"),
            sound_6: StaticSoundData::from_file("sounds/6.ogg").expect("ACK"),
            sound_7: StaticSoundData::from_file("sounds/7.ogg").expect("ACK"),
            sound_8: StaticSoundData::from_file("sounds/8.ogg").expect("ACK"),
            sound_9: StaticSoundData::from_file("sounds/9.ogg").expect("ACK"),
        }
    }

    pub fn sound_for_key(&mut self, key_press: Key) -> Option<StaticSoundData> {
        let rate = self.next_playback_rate;
        self.next_playback_rate = self.rng.random_range(VOICE_RANGE);
        match key_press {
            KeyA => Some(self.sound_a.playback_rate(rate)),
            KeyB => Some(self.sound_b.playback_rate(rate)),
            KeyC => Some(self.sound_c.playback_rate(rate)),
            KeyD => Some(self.sound_d.playback_rate(rate)),
            KeyE => Some(self.sound_e.playback_rate(rate)),
            KeyF => Some(self.sound_f.playback_rate(rate)),
            KeyG => Some(self.sound_g.playback_rate(rate)),
            KeyH => Some(self.sound_h.playback_rate(rate)),
            KeyI => Some(self.sound_i.playback_rate(rate)),
            KeyJ => Some(self.sound_j.playback_rate(rate)),
            KeyK => Some(self.sound_k.playback_rate(rate)),
            KeyL => Some(self.sound_l.playback_rate(rate)),
            KeyM => Some(self.sound_m.playback_rate(rate)),
            KeyN => Some(self.sound_n.playback_rate(rate)),
            KeyO => Some(self.sound_o.playback_rate(rate)),
            KeyP => Some(self.sound_p.playback_rate(rate)),
            KeyQ => Some(self.sound_q.playback_rate(rate)),
            KeyR => Some(self.sound_r.playback_rate(rate)),
            KeyS => Some(self.sound_s.playback_rate(rate)),
            KeyT => Some(self.sound_t.playback_rate(rate)),
            KeyU => Some(self.sound_u.playback_rate(rate)),
            KeyV => Some(self.sound_v.playback_rate(rate)),
            KeyW => Some(self.sound_w.playback_rate(rate)),
            KeyX => Some(self.sound_x.playback_rate(rate)),
            KeyY => Some(self.sound_y.playback_rate(rate)),
            KeyZ => Some(self.sound_z.playback_rate(rate)),
            Num0 => Some(self.sound_0.playback_rate(rate)),
            Num1 => Some(self.sound_1.playback_rate(rate)),
            Num2 => Some(self.sound_2.playback_rate(rate)),
            Num3 => Some(self.sound_3.playback_rate(rate)),
            Num4 => Some(self.sound_4.playback_rate(rate)),
            Num5 => Some(self.sound_5.playback_rate(rate)),
            Num6 => Some(self.sound_6.playback_rate(rate)),
            Num7 => Some(self.sound_7.playback_rate(rate)),
            Num8 => Some(self.sound_8.playback_rate(rate)),
            Num9 => Some(self.sound_9.playback_rate(rate)),
            _ => None,
        }
    }
}
